# Generated by Django 4.2.3 on 2023-07-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('passport_series_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.client')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.creditoffer')),
                ('amount_credit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payment_schedule', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('repayment_amount_body', models.DecimalField(decimal_places=2, max_digits=11)),
                ('repayment_amount_interest', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
