# Generated by Django 4.2.3 on 2023-07-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_series_number',
            field=models.CharField(max_length=10),
        ),
    ]
